services:
  frontend-angular:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ENV=development  # Configura el entorno en el build
    ports:
      - "4200:4200"  # Expone el puerto 4200 del contenedor en el 4200 del host
    restart: always
    environment:
      - NODE_ENV=development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
