name: Build & Deploy to GitHub Pages

on:
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clean previous build
        run: rm -rf dist  # 🔹 Limpia archivos viejos antes de compilar

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Install dependencies
        run: npm ci  # 🔹 Usa 'npm ci' en lugar de 'npm install' para una instalación limpia

      - name: Build
        run: npm run build -- --configuration=production

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npm run ng -- deploy --repo=https://github.com/Nayid4/FrontendGestionDeTareas.git --name="Nayid4" --email="nayid2004@gmail.com" --base-href=/FrontendGestionDeTareas/
